### ISSUE TITLE
Inbox

### ISSUE THREAD

**Issue by bijanbwb** [elixir-elm-tutorial/platform#1]
### TODO

- [x] Create GitHub org and repo for application.
- [x] Generate initial Phoenix 1.3 application.
- [x] Deploy to Heroku.
- [x] Fix for static asset buildpack to get updated for Phoenix 1.3 ([PR](https://github.com/gjaldon/heroku-buildpack-phoenix-static/pull/58)).
- [x] Configure `Procfile` to automatically handle database migrations.
- [x] Set up TravisCI builds and add badge to README.
- [x] Configure TravisCI to automatically deploy to Heroku.
- [x] Use authentication chapter from Programming Phoenix to build player auth.
- [x] Create `games` JSON resource on the Phoenix side.
- [x] Add credo to application.
- [x] Start layout and styling changes.
- [x] Consider switch to `coherence` for authentication.
- [x] Try out FullStory.
- [x] Configure Google Analytics.
- [x] Add Slack integrations for FullStory and Google Analytics.
- [x] Post in Slack for clarification on communicating bounded contexts.
- [x] Move book tasks to [book repository](https://github.com/elixir-elm-tutorial/elixir-elm-tutorial-book/issues).
- [x] Migrate project management to [PivotalTracker](https://www.pivotaltracker.com/projects/1998367).
